### ISSUE TITLE
Can you please help me fix this error?

### ISSUE THREAD

**Issue by DBabitha** [egenn/rtemis#20]
![Additive tree](https://user-images.githubusercontent.com/54527524/73348751-f37d3300-42af-11ea-97c3-7eee63ea124a.png)

**Comment by egenn** [comment]
Hi - it looks like you are missing the crayon package. Can you check whether it is installed and can be loaded?

**Comment by DBabitha** [comment]
Hi - I have installed the crayon package and it worked.But a new error has come.
![error_2](https://user-images.githubusercontent.com/54527524/73367359-7664b480-42d5-11ea-8e65-5f9ba118bb92.png)

**Comment by egenn** [comment]
Have you installed the package using `remotes::install_github("egenn/rtemis")`?
Are you loading the package using `library(rtemis)`?
I can see from your workspace you have loaded each function of the package, which will never work.
You must load the package using `library` and not source any individual files.
What is the output of `search()`?

**Comment by DBabitha** [comment]
![error_3](https://user-images.githubusercontent.com/54527524/73419045-ba8e9e00-4343-11ea-869b-93c4f2c6c2ae.png)
![error_4](https://user-images.githubusercontent.com/54527524/73419049-bcf0f800-4343-11ea-8778-3478af12e7a9.png)
Object rtenv not found.

**Comment by egenn** [comment]
Yes, you must clear your workspace.
I don't know why you have sourced individual functions into your global environment, but
notice the warning when you load the library: a long list of functions is masked by .GlobalEnv - that causes the error.
Clear your workspace and try again.

**Comment by DBabitha** [comment]
Thanks a lot,
It worked perfectly on my system but when i tested it on colab, it gave me this error
![image](https://user-images.githubusercontent.com/54527524/73422853-473f5900-4350-11ea-9791-df61bab0cd5e.png)

**Comment by egenn** [comment]
Glad it worked. 
The error on colab says it is missing the data.tree dependency
