### ISSUE TITLE
plotVarImp() fails with missing value error in if (bipolar)

### ISSUE THREAD

**Issue by jonas-sk** [egenn/rtemis#26]
Hey! Apologies for submitting so many issues. When I train an AddTree on the cases_test dataset and try to plot variable importance, it fails. 

Example:

```
cases_test.tree <- read_csv("cases_test.csv") %>% 
  preprocess(numeric2factor = TRUE) %>% 
  s.ADDTREE()

cases_test.tree$plotVarImp()
```

fails with: 

```
Error in if (bipolar) { : missing value where TRUE/FALSE needed
```

**Comment by egenn** [comment]
No worries - This is because there is no variable importance output by ADDTREE at the moment.
If you check `cases_test.tree$varimp`, it's empty.
Soon, `plotVarImp` will output an informative message stating as much.

**Comment by egenn** [comment]
Using 40edd33537cd8467635fe4ac67dfcdf043c422b1, you now get:

```
cases_test.tree$plotVarImp()
Warning message:
In cases_test.tree$plotVarImp() :
  Variable importance is not available for this model
```

**Comment by jonas-sk** [comment]
thanks for adding the warning!
