### ISSUE TITLE
outdir/rtMod.out fails on Windows

### ISSUE THREAD

**Issue by jonas-sk** [egenn/rtemis#27]
(another issue, sorry). When specifying an outdir on Windows 10, the command will fail in error. 

```
cases_test.tree <- read_csv("cases_test.csv") %>% 
  preprocess(numeric2factor = TRUE) %>% 
  s.ADDTREE(outdir = "test")
```
results in:
```
Error in file(file, if (append) "a" else "w") : cannot open the connection
```

It is probably related to the handling of Windows filepaths (e.g. https://stackoverflow.com/questions/17156445/why-i-get-this-error-writing-data-to-a-file)

**Comment by egenn** [comment]
Unfortunately, I do not have a Windows machine to work on this.
You can add an extra line to save the model and any plots you want directly.
