### ISSUE TITLE
s.ADDTREE couldn't finish when argument prune is set to FALSE

### ISSUE THREAD

**Issue by adwiputra** [egenn/rtemis#29]
Hi, I have identified a potential bug when tuning additive tree with argument "prune" is set to FALSE. The process stopped after running for a while with the console showing the sign "?". Any attempt to respond to this, i.e. by providing TRUE or FALSE, will cause the R session to encounter a fatal error.

**Comment by egenn** [comment]
Hi, thanks for the note. The `prune` argument was included for development purposes and will be removed as it should always be set to `TRUE`. Importantly, **it does not alter the tree's predictions**, only cleans up nonsense paths, like when two sister nodes have the same prediction. i.e. it is nothing like cost-complexity pruning in CART, for example.
