### ISSUE TITLE
`mplot3.xy` does not respect `ylim` when adding `fit`

### ISSUE THREAD

**Issue by stnava** [egenn/rtemis#30]
example below builds on the documentation code.

this:
```
  mplot3.xy(x, list(squared = ysq, cubed = ycu), fit = "gam",ylim=c(-20,20))

````
versus
```
  mplot3.xy(x, list(squared = ysq, cubed = ycu), ylim=c(-20,20))
```

would expect limits to be -20, 20 in both cases.  not sure if this is intended behavior.

based on `remotes` install this AM.

**Comment by egenn** [comment]
Thank you, Brian!
ee58a70f3abfbd42b5bc590f6b1a33e73ddb0cf8 should fix this.

Stathis

**Comment by stnava** [comment]
perfect thanks!
