### ISSUE TITLE
Error installation package

### ISSUE THREAD

**Issue by frequena** [egenn/rtemis#32]
Hello @egenn,

I cannot install the package. It seems related to your latest commit.

I send you below the error message:

```
* installing *source* package ‘rtemis’ ...
** using staged installation
** R
Error in parse(outFile) : 
  /tmp/RtmpJTUnXV/R.INSTALL315c7458aaa42/rtemis/R/glm2table.R:26:34: unexpected input
25:              do.call(rbind,
26:                      c(lapply(x, \
                                     ^
```

Thank you very much!

**Comment by egenn** [comment]
Thank you - it's because the glm2table function was written with the new lambda function syntax which requires R 4.1.
3c01a6dc4c9f95b426a4c2664b8bc51d4304478d fixes that and uses the standard syntax.

**Comment by frequena** [comment]
Thank you very much for your *really* quick response!

It works perfectly!
