### ISSUE TITLE
Linear Model Wrapper not Ported

### ISSUE THREAD

**Issue by abresler** [egenn/rtemis#42]
Stathis,

Looks like LM and a couple of other functions aren't ported to the new s_ API {looks like s.GLS, s.H20GBM, s.H20RF, s.IRF, s.KNN, s.LDA, s.LOESS, s.NBAYES, s.RLM} are not yet ported and break using rtemis::learn.

Thanks for the amazing work!

**Comment by egenn** [comment]
Thanks a lot, Alex. Yes, hadn't finished cleaning up.
Should be good now with 39f7b5c12e5fc67e54842974705720d93b85c532. 
Of course, let me know if any other issues come up.

All the best
