### ISSUE TITLE
resampler != "loocv"

### ISSUE THREAD

**Issue by kns1966** [egenn/rtemis#46]
Not thinking, I updated my installation today, which has resulted in the following error in previously working code. I'm using elevate() to run RANGER, GBM, and so on.

*Error in if (resampler != "loocv") { : argument is of length zero*

Tomorrow, I'll try to reproduce the error by running tutorial examples.  Posting now in the event there is a quick solution.

**Comment by egenn** [comment]
Hi, thanks for posting. 
`elevate()` has been replaced by `train()` (https://rtemis.lambdamd.org/Train.html)
Check out its usage, some arguments have been renamed for clarity, e.g. `alg` to choose algorithm and `train.params` to define hyperparameters.

**Comment by kns1966** [comment]
Thank you.
