### ISSUE TITLE
CLEANUP: It looks like package 'prprcss' doesn't exist and it can be dropped anyways

### ISSUE THREAD

**Issue by HenrikBengtsson** [egenn/rtemis#47]
The following can be dropped:

https://github.com/egenn/rtemis/blob/990a197d78c3c62c16463fa702b61a0dbb1577b1/DESCRIPTION#L95

It's not used in the package as far as I can tell.

**Comment by egenn** [comment]
Thanks - that's one of my packages for working with MRI data. Some of the rtemis functions were moved there to reduce package size, but prprcss has a few non-CRAN dependencies. Seems I was in the middle of cleaning that. Removed it (47f7ba8).
