### ISSUE TITLE
Suggestion: Drop LICENSE file

### ISSUE THREAD

**Issue by HenrikBengtsson** [egenn/rtemis#49]
Unless `LICENSE` file contains additional GPL (>= 3) compatible additions, it can be dropped, because it's sufficient to specify:

```
License: GPL (>= 3)
```

in the DESCRIPTION file in R package.  This is what all packages on CRAN do. I think CRAN actually asks for it to be removed, and currently `R CMD check --as-cran` dumps all of the content as NOTE.

**Comment by HenrikBengtsson** [comment]
If you want to keep it in the git repo, you can `LICENSE` to your `.Rbuildignore` file.

**Comment by egenn** [comment]
Yes, added it to `.Rbuildignore`
