### ISSUE TITLE
polars: can it be moved to your "rtemis-extra" package?

### ISSUE THREAD

**Issue by HenrikBengtsson** [egenn/rtemis#57]
The **polars** package:

* is not on CRAN (it's archived there <https://cran.r-project.org/package=polars>)
* is "only" available from R-Universe (<https://rpolars.r-universe.dev>) and GitHub (<https://github.com/pola-rs/r-polars/>)
* is under active development, e.g. Issue #51 and <https://github.com/pola-rs/r-polars/>
* is tricky to install, because it relies on Rust, for which there's yet no standard in R and CRAN. On Ubuntu 22.04, APT provides rustc 1.66.1, but **polars** requires rustc (>= 1.70), which means one has to go an extra mile to install Rust from non-standard sources

Because of this, the dependency on **polars**:

* complicates checking the package with _all_ R dependencies including those under `Suggests:`
* the alternative is to set `_R_CHECK_SUGGESTS_ONLY_=false` when testing
* complicates checking on GitHub Actions
* makes it harder to submit to CRAN, because they check with `_R_CHECK_SUGGESTS_ONLY_=true`

My suggestion is to remove **polars** as a dependency on **rtemis**.   If it can be incorporated via that other package where you moved other dependencies (rtemis-extra?), that would be much better.

If **polars** is removed, then it should be straightforward to set up package checks via GitHub Actions.

**Comment by egenn** [comment]
Agreed. My plan with packages like this has been to wait and watch their status until I start preparing for rtemis 1.0 release and CRAN submission, at which point I'd move all problematic packages to `rtemis-extra`. Might as well do that now, so GitHub Actions checks can get started. For now, I think I'll just comment out the polars part.
