### ISSUE TITLE
Put rtemis on R Universe

### ISSUE THREAD

**Issue by HenrikBengtsson** [egenn/rtemis#60]
Now when we have a package that passes `R CMD check`, it's quite easy to put **rtemis** on R Universe, so it can be installed as:

```r
install.packages("rtemis", repos = c("https://egenn.r-universe.dev", "https://cloud.r-project.org"))
```

To do this, see <https://github.com/r-universe-org/help#how-to-setup-your-personal-universe>, which boils down to:

1. create a repository named `universe`, i.e. <https://github.com/egenn/universe>

2. add a ~~`package.json`~~  `packages.json` file containing:

```json
[
    {
        "package": "rtemis",
        "url": "https://github.com/egenn/rtemis"
    }
]
```

3. Install <https://github.com/apps/r-universe/installations/new> to your GitHub account.

4. Wait at most an hour.

5. Check <https://egenn.r-universe.dev>.

I think this is a good first step towards submitting it to CRAN.

**Comment by HenrikBengtsson** [comment]
See also <https://jeroen.github.io/runiverse2021/#45> for how it works.

**Comment by HenrikBengtsson** [comment]
Just checking, did you do Step 3 above?

**Comment by egenn** [comment]
I did, yes. First I'd made an `egenn.r-universe.dev` repo, and followed step 3, then noticed the clash because of the auto-created site for the `music` package from CRAN. 
Then made a `universe` repo - different set of instructions mentioned that. Will try re-running the github app installation see if it does anything.

**Comment by HenrikBengtsson** [comment]
@jeroen, @egenn is trying to set up his own R Universe (https://github.com/egenn/universe), but the automatic one created for CRAN packages already exists (https://egenn.r-universe.dev/).  How can he make his own trump/override the one generated automatically?

**Comment by jeroen** [comment]
It does so automatically, however you made a typo. The registry file in https://github.com/egenn/universe has to be called `packages.json` (plural). It now only has a file called `package.json.

**Comment by egenn** [comment]
All good, thank you, @jeroen and @HenrikBengtsson.

**Comment by HenrikBengtsson** [comment]
Thanks @jeroen  (My bad; I made that typo in my gist above).

@egenn , I can no longer access <https://github.com/egenn/universe> - what changed?

**Comment by egenn** [comment]
Switched to https://github.com/egenn/egenn.r-universe.dev
