### ISSUE TITLE
The RuleFit column in the webpage cannot be opened

### ISSUE THREAD

**Issue by sugarballer** [egenn/rtemis#61]
![Quicker_20240630_135701](https://github.com/egenn/rtemis/assets/109599229/6801f3e7-2b2f-401e-8565-8d48ccf0d75c)

**Comment by egenn** [comment]
Thanks, the documentation has been recompiled and also has a new address:
[rtemis.org/rtemis](https://rtemis.org/rtemis).
The old site redirects there.
The RuleFit.html page was present but for some reason not being served by GitHub pages, I've seen this issue occur randomly a few times.
