### ISSUE TITLE
tibble / data.table friendliness

### ISSUE THREAD

**Issue by abresler** [egenn/rtemis#7]
First off -- this is one of the most incredible packages I have ever seen.  I cannot thank you enough for your hard work on this package, what you have built is nothing short of remarkable.

One thing that could be super beneficial as more and more people find out about rtemis is making sure it can jive with tibble/data.table inputs.  I have seen that it will sometimes work ok with tibbles but in other cases it appears to break.  This may also help you speed up the package, I have to think that people from the tidyverse and data.table communities maybe to help with this.

**Comment by egenn** [comment]
Thank you, Alex, for the kind words.

I have been thinking about this - I would switch all internal operations to use data.table for the improved speed and the added functionality but many/most functions from other packages wouldn't support it and require a lot of back and forth conversions to data.frame or matrix.

Commit e4190d196e504ce6fb7f68a27f5188294094a9b9 should at least make all supervised and unsupervised learning functions (`s.`, `u.` and `d.`) work with tibble or data.table inputs (simply by converting to data.frame or matrix as necessary). I will look at the visualization functions as well when I get a chance.

**Comment by egenn** [comment]
@abresler, I will close this for now - happy to discuss more
